name: Swift

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Build
      env:
        VARIABLE: ${{ secrets.YOUR_SECRET_NAME }}
        TEST: "I am a test"
      run: |
        echo "Do we have a secret?"
        len=$(echo "$TEST" | wc -c)
        echo "$len -> $TEST <-"
