name: Swift

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Build
      env:
        TEST: ${{ secrets.MY_OTHER_SECRET }}
        MOAR_TEST: ${{ secrets.YOUR_SECRET_NAME }}
      run: |
        echo "Do we have a secret?"
        len=$(echo "$TEST" | wc -c)
        echo "$len -> $TEST <-"
        len=$(echo "$MOAR_TEST" | wc -c)
        echo "$len -> $MOAR_TEST <-"
